RubricaWeb/RubricaWeb/Models/Estudiante.cs
using RubricaWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;



namespace RubricaWeb.Models
{
    public class Estudiante
    {
        private int idEstudiante;
        private string nombreEstudiante;
        private string apellidoEstudiante;
        private int idCurso;
        private string dniEstudiante;
  
        public int IdEstudiante { get => idEstudiante; set => idEstudiante = value; }

        [Required]
        public string DniEstudiante { get => dniEstudiante; set => dniEstudiante = value; }

        [Required]
        public string NombreEstudiante { get => nombreEstudiante; set => nombreEstudiante = value; }

        [Required]
        public string ApellidoEstudiante { get => apellidoEstudiante; set => apellidoEstudiante = value; }

        [Required]
        public int IdCurso { get => idCurso; set => idCurso = value; }

        

        



    }
}

RubricaWeb/RubricaWeb/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using RubricaWeb.AccesoDatos;
using RubricaWeb.Models;
using RubricaWeb.ViewModels;

namespace RubricaWeb.Controllers
{
    public class EstudianteController : Controller
    {
        // GET: Estudiante
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CargaEstudiante()
        {
            List<VM_Curso> listaCursos = AD_ViewModel.ListaDeCursos();
            List<SelectListItem> items = listaCursos.ConvertAll(i =>
            {
                return new SelectListItem()
                {
                    Text = i.NombreCurso,
                    Value = i.IdCurso.ToString(),

                    Selected = false
                };
            });
            ViewBag.items = items;
            return View();


        }

        [HttpPost]
        public ActionResult CargaEstudiante(Estudiante model)
        {
            bool esCompleto = false;
            if (ModelState.IsValid)
            {
                bool resultado = AD_Estudiante.AgregarEstudiante(model);

                if (resultado)
                {

                    return RedirectToAction("ListadoEstudiantes", "Estudiante", new {idCurso = model.IdCurso , esCompleto});
                }
                else
                {
                    return View(model);

                }
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult ListadoEstudiantes(int idCurso, bool esCompleto)
        {
            string mensaje = "LISTADO COMPLETO DE ESTUDIANTES";

            ViewBag.Boton = esCompleto;
            ViewBag.idCurso = idCurso;
            List<VM_Curso> listaCursos = AD_ViewModel.ListaDeCursos();
            List<SelectListItem> items = listaCursos.ConvertAll(i =>
            {
                return new SelectListItem()
                {
                    Text = i.NombreCurso,
                    Value = i.IdCurso.ToString(),

                    Selected = false
                };
            });
            ViewBag.items = items;

            if (esCompleto)
            {
                List<VM_Estudiante> lista = AD_Estudiante.ListadoEstudiantes();
                ViewBag.listaEstudiantes = lista;

                ViewBag.Mensaje = mensaje;

                return View();
            }
            else
            {
                List<VM_Estudiante> lista = AD_Estudiante.ListadoEstudiantesXId(idCurso);
                
                ViewBag.listaEstudiantes = lista;
                VM_Curso curso = AD_ViewModel.ObtenerCursoXId(idCurso);
                if (lista.Count==0)
                {
                    mensaje = "No Hay Estudiantes para mostrar de " + curso.NombreCurso.ToString();


                }

                else
                {
                    mensaje = lista[0].Curso;

                }
                ViewBag.Mensaje = mensaje;
                return View();
            }
           
        }



        public ActionResult MostrarDatosEstudiante(int idEstudiante)
        {
            VM_Estudiante estudiante = AD_Estudiante.ObtenerEstudianteXId(idEstudiante);
            List<VM_Materia> lista = AD_Estudiante.ListaMateriaPorEstudiante(idEstudiante);
            ViewBag.listaMaterias = lista;

            string grafico = AD_Reportes.GraficoRendimientoEstudiante(estudiante);
            List<VM_ReporteEstudiante> temasAdeudados = AD_Reportes.ResumenMateriasAdeudadas(estudiante);
            ViewBag.TemasAdeudados = temasAdeudados;

            int cantidadTemas = temasAdeudados.Count();


            ViewBag.Grafico = grafico;

            //ViewBag.estudiante = resultado;

            return View(estudiante);

        }

        public ActionResult GraficosEstudiante(int idEstudiante)
        {
            VM_Estudiante estudiante = AD_Estudiante.ObtenerEstudianteXId(idEstudiante);

            string graficoPromedio = AD_Reportes.GraficoPromediosMaterias(idEstudiante);
            ViewBag.GraficoPromedio = graficoPromedio;

            string graficoTortaEstudiante = AD_Reportes.GraficoTortaAprobadoEstudiante(idEstudiante);
            ViewBag.GraficoTortaEstudiante = graficoTortaEstudiante;


            string grafico = AD_Reportes.GraficoRendimientoEstudiante(estudiante);

            ViewBag.GraficoRendimiento = grafico;

            return View();
        }
        public ActionResult EditarEstudiante(int IdEstudiante)
        {
            List<VM_Curso> listaCursos = AD_ViewModel.ListaDeCursos();
            List<SelectListItem> items = listaCursos.ConvertAll(i =>
            {
                return new SelectListItem()
                {
                    Text = i.NombreCurso,
                    Value = i.IdCurso.ToString(),

                    Selected = false
                };
            });
            ViewBag.items = items;


            Estudiante resultado = AD_Estudiante.EstudianteParaEditar(IdEstudiante);
            return View(resultado);

        }



        [HttpPost]
        public ActionResult EditarEstudiante(Estudiante model)
        {

            if (ModelState.IsValid)
            {
                bool resultado = AD_Estudiante.ActualizarDatosEstudiante(model);
                if (resultado)
                {

                    return RedirectToAction("MostrarDatosEstudiante", "Estudiante", new { idEstudiante = model.IdEstudiante });
                }
                else
                {
                    return View(model);
                }
            }
            return View();

        }

        public ActionResult ImpresionListado(int idCurso, bool esCompleto)
        {
            string mensaje = "LISTADO COMPLETO DE ESTUDIANTES";

            ViewBag.Boton = esCompleto;
            ViewBag.idCurso = idCurso;
            List<VM_Curso> listaCursos = AD_ViewModel.ListaDeCursos();
            List<SelectListItem> items = listaCursos.ConvertAll(i =>
            {
                return new SelectListItem()
                {
                    Text = i.NombreCurso,
                    Value = i.IdCurso.ToString(),

                    Selected = false
                };
            });
            ViewBag.items = items;

            if (esCompleto)
            {
                List<VM_Estudiante> lista = AD_Estudiante.ListadoEstudiantes();
                ViewBag.listaEstudiantes = lista;

                ViewBag.Mensaje = mensaje;

                return View(lista);
            }
            else
            {
                List<VM_Estudiante> lista = AD_Estudiante.ListadoEstudiantesXId(idCurso);

                ViewBag.listaEstudiantes = lista;
                VM_Curso curso = AD_ViewModel.ObtenerCursoXId(idCurso);
                if (lista.Count == 0)
                {
                    mensaje = "No Hay Estudiantes para mostrar de " + curso.NombreCurso.ToString();


                }

                else
                {
                    mensaje = lista[0].Curso;

                }
                ViewBag.Mensaje = mensaje;
                ViewBag.Curso = mensaje;
                return View();
            }           


        }

        public ActionResult Print(int idCurso, bool esCompleto)
        {
            VM_Curso curso = AD_ViewModel.ObtenerCursoXId(idCurso);
         
            string nombreCurso= Regex.Replace(curso.NombreCurso, @"[^\w\s.!@$%^&*()\-\/]+", "");
            return new ActionAsPdf("ImpresionListado", new { idCurso, esCompleto}) { FileName = "Listado de Estudiantes de " + nombreCurso + ".pdf" };

        }






















    }





}

RubricaWeb/RubricaWeb/Controllers/ReporteController.cs
using Rotativa;
using RubricaWeb.AccesoDatos;
using RubricaWeb.Models;
using RubricaWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RubricaWeb.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LibretaEstudiante(int idEstudiante)
        {
            Estudiante nuevoEstudiante = AD_Estudiante.EstudianteParaEditar(idEstudiante);

            
            List<VM_LibretaEstudiante> libreta = AD_Reportes.ObtenerNotasLibreta(nuevoEstudiante);
            ViewBag.Estudiante = nuevoEstudiante;

            VM_Estudiante estudiante = AD_Estudiante.ObtenerEstudianteXId(idEstudiante);
            List<VM_ReporteEstudiante> temasAdeudados = AD_Reportes.ResumenMateriasAdeudadas(estudiante);
            ViewBag.TemasAdeudados = temasAdeudados;
            

            foreach (var materia in libreta)
            {
                int CantidadTemasCargados = AD_Rubrica.ContarTemasMateria(materia.idMateria);
                double promedio = 0;

                promedio = AD_Reportes.CalcularPromedioLibreta(materia, CantidadTemasCargados);
                materia.Promedio = promedio;

            }

            return View(libreta);
        }




        //////IMPRESION LIBRETA ESTUDIANTE /////////
        
        public ActionResult Print(int idEstudiante)
        {
            Estudiante nuevoEstudiante = AD_Estudiante.EstudianteParaEditar(idEstudiante);

            return new ActionAsPdf("VistaImpresionLibreta", new { idEstudiante }) { FileName = "Libreta Estudiante"+"Dni"+nuevoEstudiante.IdCurso + nuevoEstudiante.DniEstudiante+nuevoEstudiante.ApellidoEstudiante + nuevoEstudiante.NombreEstudiante +".pdf" };

        }


        public ActionResult VistaImpresionLibreta(int idEstudiante)
        {
            Estudiante nuevoEstudiante = AD_Estudiante.EstudianteParaEditar(idEstudiante);
            List<VM_LibretaEstudiante> libreta = AD_Reportes.ObtenerNotasLibreta(nuevoEstudiante);
            ViewBag.Estudiante = nuevoEstudiante;


            foreach (var materia in libreta)
            {
                int CantidadTemasCargados = AD_Rubrica.ContarTemasMateria(materia.idMateria);
                double promedio = 0;

                promedio = AD_Reportes.CalcularPromedioLibreta(materia, CantidadTemasCargados);
                materia.Promedio = promedio;

            }


            VM_Estudiante estudiante = AD_Estudiante.ObtenerEstudianteXId(idEstudiante);
            List<VM_ReporteEstudiante> temasAdeudados = AD_Reportes.ResumenMateriasAdeudadas(estudiante);
            ViewBag.TemasAdeudados = temasAdeudados;

            //int cantidad = temasAdeudados.Count();

            return View(libreta);

        }
    }
}

RubricaWeb/RubricaWeb/Views/Estudiante/CargaEstudiante.cshtml
@model RubricaWeb.Models.Estudiante


@{
    ViewBag.Title = "CargaEstudiante";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;

}



<!--<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>rubrica</title>-->
@*<link href="~/Content/rubrica.css" rel="stylesheet" id="bootstrap-css">*@
<!--<link href="~/Content/libreta-listado-rubrica.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>
<body class="container-fluid">-->



@using (Html.BeginForm())
{
    <form>
        <div class="container mt-3" style="background-color:rgba(255, 255, 255, 0.82)">
            <h2 class="text-center font-weight-bolder m-4">Agregar Estudiante</h2>
            <div class="row mb-4">
                <div class="col">
                    <div class="form-outline">

                        @Html.TextBoxFor(model => model.NombreEstudiante, htmlAttributes: new { @class = "form-control", @id = "txtNombreEstudiante", required = "required", type = "Text" })
                        <label class="form-label text-lg-center" for="form3Example1">Nombre</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        @Html.TextBoxFor(model => model.ApellidoEstudiante, htmlAttributes: new { @class = "form-control", @id = "txtApellidoEstudiante", required = "required", type = "Text" })
                        <label class="form-label text-center" for="form3Example2">Apellido</label>
                    </div>
                </div>
            </div>

            <!-- Dni input-->
            <div class="row mb-4">
                <div class="col">
                    <div class="form-outline mb-4">
                        @Html.TextBoxFor(model => model.DniEstudiante, htmlAttributes: new { @class = "form-control", @id = "txtDniEstudiante", required = "required", type = "Text" })
                        <label class="form-label text-center" for="form3Example3">Numero de Documento</label>
                    </div>
                </div>

                <!-- Curso DropDownList-->
                <div class="col">
                    <div class="form-outline mb-4">
                        @Html.DropDownList("IdCurso", items, "Elija un Curso", htmlAttributes: new { @class = "form-control", required = "required" })

                        @*<label class="form-label" for="form3Example4">Password</label>*@
                    </div>
                </div>

            </div>

            <!-- CargarButton-->
            <div class="container">
                <div class="row">
                    <div class="col text-center mb-4">
                        <button type="submit" class="btn btn-primary">Cargar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>




}


@*</body>
    </html>*@

RubricaWeb/RubricaWeb/Views/Estudiante/EditarEstudiante.cshtml
@model RubricaWeb.Models.Estudiante


@{
    ViewBag.Title = "CargaEstudiante";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;

}



@using (Html.BeginForm())
{
    <form>
        <div class="container mt-4" style="background-color:rgba(255, 255, 255, 0.82)">
            <h2 class="text-center font-weight-bolder mt-4">Editar Estudiante</h2>
            <div class="row mb-4">
                <div class="col">
                    <div class="form-outline">

                        @Html.TextBoxFor(model => model.NombreEstudiante, htmlAttributes: new { @class = "form-control", @id = "txtNombreEstudiante", type = "Text" })
                        <label class="form-label text-lg-center" for="form3Example1">Nombre</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        @Html.TextBoxFor(model => model.ApellidoEstudiante, htmlAttributes: new { @class = "form-control", @id = "txtApellidoEstudiante", type = "Text" })
                        <label class="form-label text-center" for="form3Example2">Apellido</label>
                    </div>
                </div>
            </div>

            <!-- Dni input-->
            <div class="row mb-4">
                <div class="col">
                    <div class="form-outline mb-4">
                        @Html.TextBoxFor(model => model.DniEstudiante, htmlAttributes: new { @class = "form-control", @id = "txtDniEstudiante", type = "Text" })
                        <label class="form-label text-center" for="form3Example3">Numero de Documento</label>
                    </div>
                </div>

                <!-- Curso DropDownList-->
                <div class="col">
                    <div class="form-outline mb-4">
                        @Html.DropDownList("IdCurso", items, "Elija un Curso", htmlAttributes: new { @class = "form-control" })
                        @*<label class="form-label" for="form3Example4">Password</label>*@
                    </div>
                </div>

            </div>

            <!-- CargarButton-->
            <div class="container">
                <div class="row">
                    <div class="col text-center mb-4">
                        <button type="submit" class="btn btn-primary">Cargar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>




}

RubricaWeb/RubricaWeb/Views/Estudiante/GraficosEstudiante.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<body class="bg-white">



    <div class="container-fluid bg-white">

        <div class="row  p-3">
            <div class="col-12 m-0 p-0 d-flex">
                <div class="col-6 m-0 p-0  rounded ">
                    <div id="top_x_div" style="width: 100%; height: 500px;"></div>
                </div>
                <div class="col-6 rounded m-0 p-0 ">
                    <div id="piechart_3d" style="width: 100%; height: 500px;"></div>
                </div>
            </div>


        </div>
        <div class="row p-3">
            <div class="col-12  rounded m-0 p-0 ">
                <div id="chart_div" style=" width: 100%; height:500px"></div>
            </div>

        </div>
    </div>




    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['bar'] });
        google.charts.setOnLoadCallback(drawStuff);

        function drawStuff() {
            var data1 = new google.visualization.arrayToDataTable(@Html.Raw(ViewBag.GraficoPromedio))
            //    ([
            //    ['Opening Move', 'Percentage'],
            //    ["King's pawn (e4)", 44],
            //    ["Queen's pawn (d4)", 31],
            //    ["Knight to King 3 (Nf3)", 12],
            //    ["Queen's bishop pawn (c4)", 10],
            //    ['Other', 3]
            //]);

            var options1 = {
                title: 'PROMEDIO SIN APLAZOS',
                width: 900,
                legend: { position: 'none' },
                //format:'#,##',
                //chart: {
                //    title: 'Chess opening moves',
                //    subtitle: 'popularity by percentage'
                //},
                bars: 'Vertical', // Required for Material Bar Charts.
                axes: {
                    x: {
                        0: { side: 'top', label: 'Promedio Por Materia (sin Contar Aplazos)' } // Top x-axis.
                    }
                },
                bar: { groupWidth: "90%" }
            };

            var chart = new google.charts.Bar(document.getElementById('top_x_div'));
            chart.draw(data1, options1);
        };
    </script>
    <script type="text/javascript">
        @***********************@
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart2);

        function drawChart2() {



            var data = google.visualization.arrayToDataTable(@Html.Raw(ViewBag.GraficoTortaEstudiante));

                //([
                //['Desaprobados', 'Aprobados'],
                //['Desaprobados', 6],
                //['Aprobados', 1]
                //]);

            //[['Desaprobados', 'Aprobados'], ['    ,][['Desaprobados', 'Aprobados'], ['5', 2],]

            @*"[['Desaprobados', 'Aprobados'],['Des',6],],['Apro',1],] (@Html.Raw(ViewBag.Grafico));"*@

            var options = {
                title: 'Porcentajes de Materias Aprobadas',
                is3D: true,
                pieSliceText: 'label'
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
            chart.draw(data, options);
        }


    </script>
    @*<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>*@
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable(@Html.Raw(ViewBag.GraficoRendimiento));
        //    ([
        //    ['Year', 'Sales', 'Expenses'],
        //    ['2013', 1000, 400],
        //    ['2014', 1170, 460],
        //    ['2015', 660, 1120],
        //    ['2016', 1030, 540]
        //]);
        @*(@Html.Raw(ViewBag.Grafico));*@


        var options = {
            widht: 9,
            height: 500,
            title: 'Evolucion Notas',
            hAxis: { title: 'Temas', titleTextStyle: { color: '#333' } },
            vAxis: { title: 'Notas', minValue: 0, maxValue: 11 },
          //chartArea: { left: 10, top: 10, width: '50%', height: '75%' }
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data,options);
    }

    </script>

</body>

RubricaWeb/RubricaWeb/Views/Estudiante/ImpresionListado.cshtml
@model  List<RubricaWeb.ViewModels.VM_Estudiante>

@{
    ViewBag.Title = "ImprimirLibreta";
    Layout = null;


    List<RubricaWeb.ViewModels.VM_Estudiante> itemsEstudiantes = (List<RubricaWeb.ViewModels.VM_Estudiante>)ViewBag.listaEstudiantes;
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
   

    //List<SelectListItem> combo = (List<SelectListItem>)ViewBag.comboCriterios;

    //RubricaWeb.ViewModels.VM_Tema tema = ViewBag.datosTema;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>rubrica</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/impresionLista.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>
<body class="">

    <div class="container text-center">

        <h1 class="text-center text-dark fw-bolder"> Listado de @ViewBag.Curso</h1>

        @using (Html.BeginForm())
        {
            <div class="row text-center d-inline-flex ">

                <table class="table  m-0 p-0">

                    <thead>
                        <tr class="justify-content-center small bg-info">
                            <th>N°</th>
                            <th>LEGAJO</th>
                            <th scope="row" class="">APELLIDO Y NOMBRE</th>
                            <th>DNI</th>
                            <th>CURSO</th>
                        </tr>
                    </thead>
                    <tbody class="">
                        @{ int nros = 1;
                            foreach (var item in itemsEstudiantes)
                            {
                                <tr class="">
                                    <td class=" p-2">@(nros ++)</td>
                                    <td class=" p-2">@(item.IdEstudiante)</td>
                                    <td class=" p-2">@(item.NombreCompleto)</td>
                                    <td class=" p-2"> @(item.Dni)</td>
                                    <td class=" p-2"> @(item.Curso)</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>

            </div>
        }
    </div>


    <p class="font-weight-bold float-right m-3"> Fecha de Impresión: @DateTime.Now.ToString()</p>
</body>
</html>

RubricaWeb/RubricaWeb/Views/Estudiante/ListadoEstudiantes.cshtml
@model IEnumerable<RubricaWeb.ViewModels.VM_Estudiante>


@{
    //ViewBag.Title = "ListadoEstudiantes";
    List<RubricaWeb.ViewModels.VM_Estudiante> itemsEstudiantes = (List<RubricaWeb.ViewModels.VM_Estudiante>)ViewBag.listaEstudiantes;
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;


}



@using (Html.BeginForm())

{
    //int contador = 1;
    int index = 1;
    <div class=" container mt-2">
        <div class="col-10 ">
            <h2 class="text-center font-weight-bolder" style="background-color:rgba(255, 255, 255, 0.82)"> @ViewBag.Mensaje </h2>
            <div class="row mb-4">
                <div class="col-12 h6 align-content-end">
                    @Html.DropDownList("IdCurso", items, "Filtrar por Curso", htmlAttributes: new { @class = "form-control h6", @onchange = "Refresh()", @id = "IdCurso" })
                </div>
             
                <table class="table bg-light border-1 table-hover rounded " id="tabla">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">
                                N°
                            </th>
                            <th class="text-center">
                                Apellido y Nombre
                            </th>
                            <th class="text-center">
                                DNI
                            </th>
                            <th class="text-center">
                                Curso
                            </th>
                            <th class="text-center">
                                Acciones
                            </th>
                        </tr>
                    </thead>
                    @foreach (var item in itemsEstudiantes)
                    {
                        <tbody>
                            <tr class="text-center align-items-center">
                                <td class="align-middle">  @(index++) </td>
                                <td class="align-middle">
                                    @Html.DisplayFor(Model => item.NombreCompleto)
                                </td>
                                <td class="align-middle">
                                    @Html.DisplayFor(Model => item.Dni)
                                </td>
                                <td class="align-middle">
                                    @Html.DisplayFor(Model => item.Curso)
                                </td>
                                <td class="align-middle">
                                    <div class="row">
                                        <div class="col-4">
                                            <a href="@Url.Action("EliminarEstudiante", "Estudiante", new { @IdEstudiante = item.IdEstudiante })" style="width:20px; height:20px;" class=" text-danger" title="Eliminar"><i class="fas fa-user-slash"></i> <br /> Eliminar</a>
                                        </div>
                                        <div class="col-4">
                                            <a href="@Url.Action("MostrarDatosEstudiante", "Estudiante", new { @IdEstudiante = item.IdEstudiante })" class="text-info"><i class="fas fa-info" data-toggle="tooltip" data-placement="top" title="Ver Info"></i> <br /> Ver Info</a>
                                        </div>
                                        <div class="col-4">
                                            <a href="@Url.Action("LibretaEstudiante", "Reporte", new { IdEstudiante = item.IdEstudiante })" class="text-info"><i class="far fa-file-alt" data-toggle="tooltip" data-placement="top" title="Libreta"></i> <br /> Libreta</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    }

                </table>

            </div>
        </div>
    </div>

}
<div class="row text-center d-flex justify-content-center">
    @{ if (!@ViewBag.Boton)
        {
            <a href="@Url.Action("Print", "Estudiante", new { idCurso = @ViewBag.idCurso, esCompleto = ViewBag.boton })" class="btn text-dark bg-success rounded-circle p-3" title="IMPRIMIR"><i class="fas fa-print fa-3x text-light"></i></a>
        }
        <br />
    }
</div>





<script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
//Refresh();
    function Refresh() {
        var cboMateria = document.getElementById("IdCurso");
        cboMateria.addEventListener("change", Refresh);
        window.location.href = ("@Url.Content("~/Estudiante/ListadoEstudiantes")" + "?IdCurso=" + cboMateria.value + " &esCompleto=False");


    }
</script>


@*<script src="~/lib/jquery/dist/jquery-ui-1.12.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("#txtFiltro").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#tabla tr").not(':first').filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>*@